spark.master                     spark://spark-master:7077
spark.app.name                   gcip-spark-job
spark.submit.deployMode          client
spark.sql.extensions             io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog  org.apache.spark.sql.delta.catalog.DeltaCatalog